export const ROUTES = {
  HOME: "/",
  LOGIN_HOME: "/login-home",
  LOGIN: "/login",
  SIGN_UP: "/sign-up",
  REGISTER: "/register",
  REGISTER_KEYS: "/register-keys",
  DELEGATE_SETTINGS: "/delegate-settings",
  SET_CONDITIONS: "/set-conditions",
  REGISTER_CONFIRM: "/register-confirm",
  REGISTER_SUCCESS: "/register-success",
  RECOVER_KEYS: "/recover-keys",
  TRANSFER: "/transfer",
  OAUTH_RESULT: "/oauth-result",
  TEST: "/test",
};
